### ISSUE TITLE
Landscape mode does not work when application installed on mobile/tablet device

### ISSUE THREAD

**Issue by dgautherot** [Bewelge/MIDIano#49]
Hello,
First, thank you for this great piece of application !

I'm facing an issue with it when this application is installed onto android devices (like mobile phone or tablet).

When I'm using the application from a web browser, if I rotate the device to use it in landscape mode, so that the keyboard becomes bigger, then it works.

But if I install the application on the device (as it is a progressive web app, it is proposed to be installed directly onto the device, more comfortable when no internet connexion), when I rotate it, the landscape mode does not work, it remains in portrait mode and thus the keyboard remains tiny and it is difficult to play.

Can you have a look at this issue ?

Thank you.

**Comment by Bewelge** [comment]
Hey there, thanks for reporting this. I just noticed this myself yesterday. Somehow the resize callback isn't triggered when the device orientation changes. One workaround for now is to hide/show the top menu by clicking the little caret under the progress bar (see screenshot) , which will trigger the resize manually. 
![image](https://github.com/Bewelge/MIDIano/assets/17884995/d26ea21d-4fe9-4731-8af9-eba624cf441c)


That should help until I fix the bug. It also seems to only affect iOS

**Comment by dgautherot** [comment]
Hello, 
This issue arises on android devices as well, and the proposed workaround does not work. I mention that the application is installed directly onto the device, as proposed by the web browser. So in that case, the header toolbar as per your screenshot is not the same.

**Comment by Bewelge** [comment]
Ah so your issue is that the app isn't even rotating to landscape? Sorry I misunderstood that. Can't reproduce it though, both on my android and iPhone it rotates even when installed as PWA. Only iOS has an issue with not properly resizing the menu to landscape mode (but it still rotates to landscape). Will have to further investigate.

**Comment by dgautherot** [comment]
If I can help, tell me.

**Comment by Bewelge** [comment]
Can you tell me what device you are using?

**Comment by Bewelge** [comment]
So it turns out this was a bug in Chrome. It should be working now. Reopen if you're still having trouble.

**Comment by dgautherot** [comment]
I'm using Huawei Mate 20 Lite on Android 10.
When app is run from the base URL in browser, no problem to switch from portrait to lansdscape. When installed directly in android, it still doesn't switch to landscape.

**Comment by dgautherot** [comment]
I think the issue is still not solved, and should be kept opened status. (I don't know how to reopen it)

**Comment by Bewelge** [comment]
Sorry forgot to mention: You will have to uninstall the app. Then clear your cache (Settings -> Website Settings -> Website data) for app.midiano.com and then re-install. Let me know if that works.

**Comment by Bewelge** [comment]
Assuming this worked. Reopen if you still need help.
